# Generated by Django 3.1.6 on 2021-02-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GapminderObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gapminder', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('user_created', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['country', 'continent'],
            },
        ),
    ]
